# This file will overwrite settings below when "test" is included in the CSV list
# of values for "spring.profiles.active" in the main applications.properties file

guru:
  username: ymltestuser
  password: ymltestpwd
  jdbcUrl: yml.test.url.com